apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server-chart.fullname" . }}
  labels:
    {{- include "server-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "server-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "server-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: serverport
              containerPort: 3000
              protocol: TCP
          env:
          - name: MYSQL_HOST
          {{- if .Values.mariadb.enabled }}
            value: {{ .Values.mariadb.hostname | quote }}
          {{- else }}
            value: unknown
          {{- end }}
          - name: MYSQL_USER
          {{- if .Values.mariadb.enabled }}
            value: {{ .Values.mariadb.db.user | quote }}
          {{- else }}
            value: unknown
          {{- end }}
          - name: MYSQL_DATABASE
          {{- if .Values.mariadb.enabled }}
            value: {{ .Values.mariadb.db.name | quote }}
          {{- else }}
            value: unknown
          {{- end }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.mariadb.enabled }}
                name: {{ .Values.mariadb.hostname }}
                key: mariadb-password
              {{- else }}
                name: unknown
                key: db-password
              {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: serverport
          readinessProbe:
            httpGet:
              path: /ready
              port: serverport
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
