apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.hostname }}
  labels:
    {{- include "server-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.mariadb.db.password) }}
  mariadb-password: "{{ .Values.mariadb.db.password | b64enc }}"
  {{- else }}
  mariadb-password: {{ required "A MariaDB Database Password is required!" .Values.mariadb.db.password }}
  {{- end }}
